### PR TITLE
Write more tests, and misc fixes

### LINKED ISSUE #90: Write tests for `/api` and `/util` funcs
Currently, we have unit tests (which essentially test `/src/components`) and end-to-end tests (which essentially test `/src/views`), but we're lacking tests for code in `/api` and code in `/util` (slightly less critical since those functions are very simple).

The `/api` code takes in some simple parameters, transforms them into a request, gets the response, and transforms the response into the desired format. The latter of those steps I think is not as critical to test, as typescript will tell us pretty reliably when we're not returning the desired format. However we have no way of knowing if the request was constructed correctly, which is often not trivial.

`msw` does not provide a way to assert that a request was called with the correct parameters, and they strongly recommend against doing such a thing. They don't explain it, but I think their recommendation, in our case, would be to use jest to spy on the `request` function that (almost) every `/api` function calls halfway through, and assert that it was called with the correct parameters. But we also want the spyed-function to still carry out, not be a blank stub/mock, so `msw` can intercept the request and return dummy data.

### LINKED ISSUE #106: Write tests for `/api` and `/util` funcs
Currently, we have unit tests (which essentially test `/src/components`) and end-to-end tests (which essentially test `/src/views`), but we're lacking tests for code in `/api` and code in `/util` (slightly less critical since those functions are very simple).

The `/api` code takes in some simple parameters, transforms them into a request, gets the response, and transforms the response into the desired format. The latter of those steps I think is not as critical to test, as typescript will tell us pretty reliably when we're not returning the desired format. However we have no way of knowing if the request was constructed correctly, which is often not trivial.

`msw` does not provide a way to assert that a request was called with the correct parameters, and they strongly recommend against doing such a thing. They don't explain it, but I think their recommendation, in our case, would be to use jest to spy on the `request` function that (almost) every `/api` function calls halfway through, and assert that it was called with the correct parameters. But we also want the spyed-function to still carry out, not be a blank stub/mock, so `msw` can intercept the request and return dummy data.

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes monarch-initiative/monarch-api#90 

In order of commits:

- rework usequery to be a little bit simpler with respect to statuses. change components using usequery to always await fetch function, for clarity. write tests for usequery
- write tests for consequential or non-trivial util functions
-  move setting of document title around a bit. change to array. use node name for doc title when/if available. make use of `flush: post` in `watch` for route changes, per a vue-router github issue. simplify a few watch/onMounted calls in related components
- add fixture data and msw for ontol identifier endpoint (used for converting taxon label back to id for querying biolink)
- add some try/catch blocks where necessary (in intermediate async network calls like ontol identifier). fix some spelling errors and other small errors. use vue's `@` import syntax where possible. add tests for select api functions to ensure that the construct their requests correctly. write tests for facet functions.
- add notes into readme for bundle analyzing and spell checking

### CODE REVIEW

File: src/global/meta.ts [hunk 1]
```diff
@@ -8,16 +8,21 @@ import { ref, watch } from "vue";
  */
 
 /** variables */
-export const appTitle = ref(process.env.VUE_APP_TITLE);
+export const appTitle = ref([process.env.VUE_APP_TITLE]);
```
Comment (falquaddoomi) [inline src/global/meta.ts:11]: I assume you changed this to an array because a string is immutable and thus not observable, but is that the actual reason? That'd be fine, but I wanted to check.

File: src/util/composables.ts [hunk 2]
```diff
@@ -55,29 +63,17 @@ export const useQuery = <Data, Args extends Array<unknown>>(
...
         /** on success callback */
         if (onSuccess) onSuccess(result, args);
-
-        /** return results */
-        return result;
       } else {
-        /** otherwise, throw special "stale" error */
-        throw new Error("Stale query");
+        /** otherwise, log special "stale" error */
+        console.error("Stale query");
```
Comment (falquaddoomi) [inline src/util/composables.ts:68]: Again, just checking, but I assume you switched from throwing an exception to logging since de-staling is no longer something you're including in your useQuery implementation, right?

**Review by falquaddoomi — COMMENTED** [review]
I had a few clarification questions, but otherwise it all looks good. Once you get back to me on those I'll approve the PR.

File: src/global/meta.ts (hunk 1 above)
Comment (falquaddoomi) [reply src/global/meta.ts:11]: Actually, I guess that's not quite it, since `ref()` can apparently take a string...I apologize, I don't know much about the Vue composition API. I'm curious to hear why you wrap this particular string in an array and not others, like the ones immediately below it.

File: src/util/composables.ts (hunk 2 above)
Comment (vincerubinetti) [reply src/util/composables.ts:68]: This change should only be a refactor, it shouldn't change the behavior at all. I noticed that I was throwing a "stale" error in the try block, detecting it in the catch block by matching the string "stale", then just logging the error. Now, instead, I just log the error in place to clean up the code.

Comment (falquaddoomi) [reply src/util/composables.ts:68]: Aha, that makes sense. Thanks!

File: src/global/meta.ts (hunk 1 above)
Comment (vincerubinetti) [reply src/global/meta.ts:11]: Yes ref can take any data type. The reason I changed `appTitle` to an array of strings instead of just a string is just for convenience:

```ts
const title = appTitle.value
    .concat([process.env.VUE_APP_TITLE])
    .filter((part) => part)
    .join(" | ");

  document.title = title || "";
```

This makes making multi-part titles, e.g. "Node Search | Marfan Syndrome | Monarch Initiative", a little more convenient imo, rather than having to do a bunch of if's for figuring out where to put the separators. It also makes it such that you only have to specify the separator (`|`) in one place, rather than anywhere where you set `appTitle`.

Comment (falquaddoomi) [reply src/global/meta.ts:11]: Oh, duh, I didn't notice that code where you create the title from the array. Ok, that makes perfect sense, and I agree that an array is the right way to represent a title with multiple bits in it.

**Review by falquaddoomi — APPROVED** [review]

File: src/global/meta.ts (hunk 1 above)
Comment (vincerubinetti) [reply src/global/meta.ts:11]: Typescript will throw a warning if you try to set `appTitle` to just a string.

I'll make the comment above the declaration of `appTitle` more descriptive, e.g. "multi-part document title, as an array, that gets joined with | separator", so anyone who goes to set it will see that.

I'll add it to my next-next PR, since I am a few PRs ahead.
